### ISSUE TITLE
undefined method `to_sym' for {:by=>[:users], :scale=>0..5}:Hash (NoMethodError)

### ISSUE THREAD

**Issue by karamat** [upstarter/acts_as_reviewable#1]
When I called it in a Model as
acts_as_reviewable :by => [:users], :scale => 0..5

It raised "undefined method `to_sym' for {:by=>[:users], :scale=>0..5}:Hash (NoMethodError)"

/lib/reviewable_methods.rb:14:in `acts_as_reviewable'

**Comment by upstarter** [comment]
Sorry I haven't had the time to continue with development of this gem. It is in a non-working state at the moment. Feel free to submit a pull request.
