### ISSUE TITLE
Could not find generator acts_as_reviewable_migration

### ISSUE THREAD

**Issue by IslamAzab** [upstarter/acts_as_reviewable#2]
The command for generating the migration is not working. 
" rails generate acts_as_reviewable_migration "

I had to use a similar workaround mentioned here http://stackoverflow.com/questions/6532331/could-not-find-generator-acts-as-taggable-migration to make it work.

Any ideas why the original command is not working?

**Comment by Yasmine-Gaber** [comment]
Issue solved in this pull request https://github.com/rubycoder1/acts_as_reviewable/pull/3
